// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240102103852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Data.Entities.BookEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Page_No")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("publication_date");

                    b.Property<string>("PublishingHouse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Bolesław Prus",
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(519),
                            ISBN = "1234567890",
                            LibraryId = 1,
                            Page_No = "800",
                            Priority = 1,
                            PublicationDate = new DateTime(1890, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishingHouse = "Wydawnictwo Epoka",
                            Title = "Lalka"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Adam Mickiewicz",
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(569),
                            ISBN = "2345678901",
                            LibraryId = 1,
                            Page_No = "340",
                            Priority = 1,
                            PublicationDate = new DateTime(1834, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishingHouse = "Wydawnictwo Narodowe",
                            Title = "Pan Tadeusz"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Witold Gombrowicz",
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(579),
                            ISBN = "3456789012",
                            LibraryId = 1,
                            Page_No = "300",
                            Priority = 1,
                            PublicationDate = new DateTime(1937, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishingHouse = "Wydawnictwo Literackie",
                            Title = "Ferdydurke"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Eliza Orzeszkowa",
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(587),
                            ISBN = "4567890123",
                            LibraryId = 1,
                            Page_No = "450",
                            Priority = 1,
                            PublicationDate = new DateTime(1888, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PublishingHouse = "Wydawnictwo Zielona Sowa",
                            Title = "Nad Niemnem"
                        });
                });

            modelBuilder.Entity("Data.Entities.BorrowEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("UserId");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("Data.Entities.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Birth")
                        .HasColumnType("TEXT")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birth = new DateTime(2000, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(596),
                            Email = "adam@wsei.edu.pl",
                            Name = "Adam",
                            OrganizationId = 1,
                            Phone = "127813268163",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            Birth = new DateTime(1999, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2024, 1, 2, 11, 38, 52, 480, DateTimeKind.Local).AddTicks(599),
                            Email = "ewa@wsei.edu.pl",
                            Name = "Ewa",
                            OrganizationId = 3,
                            Phone = "293443823478",
                            Priority = 2
                        });
                });

            modelBuilder.Entity("Data.Entities.OrganizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("organizations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Uczelnia",
                            Name = "WSEI"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Uczelnia",
                            Name = "PJTAK"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Korporacja",
                            Name = "ABB"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Szkoła średnia",
                            Name = "Technikum Informatyczne w Poznaniu"
                        });
                });

            modelBuilder.Entity("LibraryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Główna biblioteka na terenie Wyższej Szkoły Ekonomii i Informatyki",
                            Name = "Biblioteka Główna WSEI"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Biblioteka publiczna przy Polsko-Japońskiej Akademii Technik Komputerowych",
                            Name = "Biblioteka Publiczna PJTAK"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Biblioteka korporacyjna ABB",
                            Name = "Biblioteka ABB"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Biblioteka szkolna przy Technikum Informatycznym w Poznaniu",
                            Name = "Biblioteka Technikum Informatycznego w Poznaniu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c860a04c-159b-440f-9096-c3e15377d9bb",
                            ConcurrencyStamp = "c860a04c-159b-440f-9096-c3e15377d9bb",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4a7e5705-0a0f-4e38-b169-f7c4d32a8cb4",
                            ConcurrencyStamp = "33af9030-02b1-406c-ae3e-7958d95ccfc0",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9b40da3d-39aa-453f-b41e-e497cced4a01",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38db338c-2c81-48cc-b9a5-146f841648d1",
                            Email = "test@test.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TEST@TEST.PL",
                            NormalizedUserName = "TEST@TEST.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAELJOUBFjb/4KcG/EGuSMZan/tPs5TpHhTujZt/1iPjh2EzW3iLe821bHWUof7SrIWQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d674a31d-4026-42e2-b668-6be4316d5e37",
                            TwoFactorEnabled = false,
                            UserName = "test@test.pl"
                        },
                        new
                        {
                            Id = "37a02f36-d78d-42d4-8871-2ff93b99295f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "159b1db8-8909-4dbc-b097-60ec7f2e6213",
                            Email = "adminek@wp.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEDHnadnmu1Wk2jjH1Ihh22QiHH5KfczOtUKEbrnJm7Pk1ejyjXIAKRGKrTcEJ3eXmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0538abd0-8dd3-4133-a8a3-370e87ce78af",
                            TwoFactorEnabled = false,
                            UserName = "adminek@wp.pl"
                        },
                        new
                        {
                            Id = "638eccae-d4c4-4190-9135-a2008e5ac012",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55e7e9c4-c80a-4ea6-8836-e8f3ea7135ae",
                            Email = "jan@przyklad.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JAN@PRZYKLAD.PL",
                            NormalizedUserName = "JAN@PRZYKLAD.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEKrg5U/g6gFBegAY43SpR4b6wtIMIv0vUiZaPXLm8nqmlfUWAU4Mw3rUqg/Jf5j+mQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "652de4b8-d973-4b22-8dc5-4ce41b900441",
                            TwoFactorEnabled = false,
                            UserName = "jan@przyklad.pl"
                        },
                        new
                        {
                            Id = "2b9da503-60ce-4adc-98df-2eac570a99af",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2c366af-b80f-4228-9d01-d0a8040e8322",
                            Email = "anna@przyklad.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ANNA@PRZYKLAD.PL",
                            NormalizedUserName = "ANNA@PRZYKLAD.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEEK+CB6OX31wpFZDFI2Wg92cUyV9hDGSbJRObueC10ih9YOe3+siBYITJ1P48dCYSw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e9dcf0c-a050-4a97-9264-f9fb002bc6e0",
                            TwoFactorEnabled = false,
                            UserName = "anna@przyklad.pl"
                        },
                        new
                        {
                            Id = "e32d1328-313d-43d0-b1af-42eb24deee58",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe5bffb1-8ab7-4111-8086-ec847b232889",
                            Email = "kasia@przyklad.pl",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "KASIA@PRZYKLAD.PL",
                            NormalizedUserName = "KASIA@PRZYKLAD.PL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFu5aDDeUhl1gjkZj/PDxT3wMsZgbhI01kQ++JOs+ngMnoAN14Fmi6jt3sHmML0gBA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e05640b-cde0-4468-b017-467b42839976",
                            TwoFactorEnabled = false,
                            UserName = "kasia@przyklad.pl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "638eccae-d4c4-4190-9135-a2008e5ac012",
                            RoleId = "4a7e5705-0a0f-4e38-b169-f7c4d32a8cb4"
                        },
                        new
                        {
                            UserId = "2b9da503-60ce-4adc-98df-2eac570a99af",
                            RoleId = "4a7e5705-0a0f-4e38-b169-f7c4d32a8cb4"
                        },
                        new
                        {
                            UserId = "e32d1328-313d-43d0-b1af-42eb24deee58",
                            RoleId = "4a7e5705-0a0f-4e38-b169-f7c4d32a8cb4"
                        },
                        new
                        {
                            UserId = "9b40da3d-39aa-453f-b41e-e497cced4a01",
                            RoleId = "c860a04c-159b-440f-9096-c3e15377d9bb"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Data.Entities.BookEntity", b =>
                {
                    b.HasOne("LibraryEntity", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Data.Entities.BorrowEntity", b =>
                {
                    b.HasOne("Data.Entities.BookEntity", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryEntity", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Data.Entities.ContactEntity", b =>
                {
                    b.HasOne("Data.Entities.OrganizationEntity", "Ogranization")
                        .WithMany("Contacts")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Ogranization");
                });

            modelBuilder.Entity("Data.Entities.OrganizationEntity", b =>
                {
                    b.OwnsOne("Data.Models.Address", "Adress", b1 =>
                        {
                            b1.Property<int>("OrganizationEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrganizationEntityId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationEntityId");

                            b1.HasData(
                                new
                                {
                                    OrganizationEntityId = 1,
                                    City = "Kraków",
                                    PostalCode = "31-150",
                                    Street = "Św. Filipa 17"
                                },
                                new
                                {
                                    OrganizationEntityId = 2,
                                    City = "Warszawa",
                                    PostalCode = "00-001",
                                    Street = "Aleje Jerozolimskie 120"
                                },
                                new
                                {
                                    OrganizationEntityId = 3,
                                    City = "Gdańsk",
                                    PostalCode = "80-001",
                                    Street = "ul. Długa 10"
                                },
                                new
                                {
                                    OrganizationEntityId = 4,
                                    City = "Poznań",
                                    PostalCode = "61-001",
                                    Street = "Stary Rynek 1"
                                });
                        });

                    b.Navigation("Adress")
                        .IsRequired();
                });

            modelBuilder.Entity("LibraryEntity", b =>
                {
                    b.OwnsOne("Data.Models.LibraryAddress", "LibraryAdress", b1 =>
                        {
                            b1.Property<int>("LibraryEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .HasColumnType("TEXT");

                            b1.HasKey("LibraryEntityId");

                            b1.ToTable("Libraries");

                            b1.WithOwner()
                                .HasForeignKey("LibraryEntityId");

                            b1.HasData(
                                new
                                {
                                    LibraryEntityId = 1
                                },
                                new
                                {
                                    LibraryEntityId = 2
                                },
                                new
                                {
                                    LibraryEntityId = 3
                                },
                                new
                                {
                                    LibraryEntityId = 4
                                });
                        });

                    b.Navigation("LibraryAdress")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("Contacts");
                });

            modelBuilder.Entity("LibraryEntity", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
